name: .NET

on:
  push:
    branches:
      - aspire-add-aspire
      - aspire-add-mongo
      - aspire-add-python
      - aspire-add-rust
      - aspire-add-web
      - aspire-dynamic-ports
      - aspire-add-opentelemetry
      - aspire-add-nodejs
      - aspire-complete
      - aspire-daily

  pull_request:
    branches:
      - aspire-add-aspire
      - aspire-add-mongo
      - aspire-add-python
      - aspire-add-rust
      - aspire-add-web
      - aspire-dynamic-ports
      - aspire-add-opentelemetry
      - aspire-add-nodejs
      - aspire-complete
      - aspire-daily

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Configuration: Release

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
